### ISSUE TITLE
我能请教您吗。。我毕设做这个。很急。希望您看到请回复我

### ISSUE THREAD

**Issue by Sea540767145** [NICE-FUTURE/predict-gender-and-age-from-camera#1]

**Comment by NICE-FUTURE** [comment]
你好！
这份代码只是我课余学习人脸识别的思路记录，目前我还不擅长于此
如果方便的话，有什么问题你可以直接在此issue提出，我尽量答复，但个人还是建议你多多参考社区里的更多优质项目，感谢你的关注~

**Comment by Sea540767145** [comment]
我毕设的方向是。用开源的人脸数据集。结合神经网络。训练出性别、年龄判断模型。
这个跟你的工程比较符合，所以就想请教你



---原始邮件---
发件人: "nice-future"<notifications@github.com&gt;
发送时间: 2020年5月16日(周六) 中午11:16
收件人: "NICE-FUTURE/predict-gender-and-age-from-camera"<predict-gender-and-age-from-camera@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Sea540767145"<540767145@qq.com&gt;;
主题: Re: [NICE-FUTURE/predict-gender-and-age-from-camera] 我能请教您吗。。我毕设做这个。很急。希望您看到请回复我 (#1)




 
你好这份代码只是我课余学习人脸识别的思路记录，目前我还不擅长于此
 如果方便的话，有什么问题你可以直接在此issue提出，我尽量答复，但个人还是建议你多多参考社区里的更多优质项目，感谢你的关注~
