### ISSUE TITLE
Please test.pth file

### ISSUE THREAD

**Issue by Simon9901** [NICE-FUTURE/predict-gender-and-age-from-camera#3]
Hello, blogger, since the computer runs very slowly during my training, I would like to ask if you still have test PTH file, can you upload and share it. Thank you very much.

**Comment by NICE-FUTURE** [comment]
Hello~ The model weights is uploaded ([download-link](https://github.com/NICE-FUTURE/predict-gender-and-age-from-camera/raw/master/middle/saved_models/test-best.pth)). Have fun~

**Comment by Simon9901** [comment]
Thank you very much!!!!
