### ISSUE TITLE
ERROR! Loss is Nan. Break

### ISSUE THREAD

**Issue by JXH-2020** [NICE-FUTURE/predict-gender-and-age-from-camera#5]
![image](https://user-images.githubusercontent.com/67779513/191655048-4a95d245-ebcd-4656-bd9f-647b994a4766.png)训练到一半的时候为什么会出现ERROR! Loss is Nan. Break.  请问作者怎么解决

**Comment by NICE-FUTURE** [comment]
出现 Nan 的可能原因蛮多的，我觉得可以先从下面几个方面排查下：

1. 数据问题。使用的数据中包含 Nan ，或者数据预处理操作产生了 Nan（如：除 0 操作）。我这个 Demo 是用的公开数据集，所以数据上应该没有这个问题。
2. 学习率过大。有时候学习率过大会出现 Nan，可以减小 10 倍试试
3. 对模型的改动不合理。比如增加了多层卷积层（`Conv2d`）但没有加入对应的归一化层（如 `BatchNorm2d`），也会产生 Nan

我目前想到的就是这几点，你可以试试看，感谢关注。

另：
`middle/log/` 文件夹下有我当时训练的日志，里面包含使用的超参数和训练过程，不知会不会有帮助，你可以看一下
