### ISSUE TITLE
权重问题

### ISSUE THREAD

**Issue by wangnanv5** [NICE-FUTURE/predict-gender-and-age-from-camera#7]
![image](https://github.com/NICE-FUTURE/predict-gender-and-age-from-camera/assets/62439985/510b07b5-8233-4d6a-9a95-55a51415abd2)
请问这种情况您遇到过么?
用的是最新的代码和最新的权重.

**Comment by NICE-FUTURE** [comment]
噢噢，有可能是会出现这种问题，因为有可能你的timm版本和我的不一样，所以导致 timm.create_model() 拿到的模型结构也会有一些区别。这样我训练得到的权重你在加载的时候就可能出现某些参数不匹配的情况。

我本地两个环境的 timm 库版本是 0.9.2 和 0.6.12，我忘记是用哪个环境训练的了，你可以试试 0.9.2 的版本。
如果不打算改环境的话，可以在加载权重的时候，把上面不匹配的这些权重剔除，作为初始化权重来使用的话应该影响不大。

**Comment by Young1108** [comment]
pip install timm==0.9.2 可解决
